name: Obsidian
version: "1.5.14"
slug: obsidian
description: A secure, self-hosted digital brain with Home Assistant integration.
url: https://github.com/adrianwedd/home-assistant-obsidian/tree/main/obsidian
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
init: false
image: ghcr.io/sytone/obsidian-remote:latest
tmpfs: true
ingress: true
ingress_port: 8080
panel_icon: mdi:brain
panel_title: Obsidian
ports: {}
backup_exclude:
  - BrowserCache/
  - .cache/
options:
  puid: 1000
  pgid: 1000
  tz: UTC
schema:
  puid: int
  pgid: int
  tz: str
