name: Obsidian
version: "v1.8.10-ls75"
slug: obsidian
description: A secure, self-hosted digital brain with Home Assistant integration.
url: https://github.com/adrianwedd/home-assistant-obsidian/tree/main/obsidian
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
init: false
image: lscr.io/linuxserver/obsidian
tmpfs: true
privileged:
  - SYS_ADMIN
devices:
  - /dev/dri
ingress: true
ingress_port: 3000
ingress_entry: "/"
panel_icon: mdi:brain
panel_title: Obsidian
ports: {}
backup_exclude:
  - BrowserCache/
  - .cache/
options:
  puid: 1000
  pgid: 1000
  tz: UTC
schema:
  puid: int
  pgid: int
  tz: str
