name: Obsidian
version: "0.1.0"
slug: obsidian
description: A secure, self-hosted digital brain with Home Assistant integration.
url: https://github.com/adrianwedd/home-assistant-obsidian
arch:
  - aarch64
  - amd64
  - armv7
init: false
image: lscr.io/linuxserver/obsidian:latest
tmpfs: true
ingress: true
ingress_port: 3000
panel_icon: mdi:brain
panel_title: Obsidian
ports: {}
watchdog: http://[HOST]:3000/
memory: 512
backup_exclude:
  - BrowserCache/
  - .cache/
map:
  - data:rw
options:
  puid: 1000
  pgid: 1000
  tz: UTC
schema:
  puid: int
  pgid: int
  tz: str
