name: Lint

on:
  push:
  pull_request:

jobs:
  addon-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: frenck/action-addon-linter@v2
        with:
          path: obsidian
