name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run add-on linter
        uses: frenck/action-addon-linter@v2
        with:
          path: ./obsidian
