name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Update version and image tag
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq
          VERSION="${GITHUB_REF_NAME#v}"
          yq -i ".version = \"${VERSION}\"" obsidian/config.yaml
          yq -i ".image = \"lscr.io/linuxserver/obsidian\"" obsidian/config.yaml

      - name: Commit files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add obsidian/config.yaml
          git commit -m "Release ${{ github.ref_name }}"
          git push

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ## Release Notes

            See [CHANGELOG.md](CHANGELOG.md) for details.
