name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Get version from tag
        id: get_version
        run: echo "version=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq && sudo chmod +x /usr/bin/yq

      - name: Update version in config.yaml
        run: |
          yq -i ".version = \"${{ steps.get_version.outputs.version }}\"" obsidian/config.yaml

      - name: Commit files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add obsidian/config.yaml
          git commit -m "Release ${{ steps.get_version.outputs.version }}"
          git push

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ## Release Notes

            See [CHANGELOG.md](CHANGELOG.md) for details.
