name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Update version and image tag
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq
          VERSION="${GITHUB_REF_NAME#v}"
          yq -i ".version = \"${VERSION}\"" obsidian/config.yaml
          yq -i ".image = \"lscr.io/linuxserver/obsidian\"" obsidian/config.yaml

      - name: Commit files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add obsidian/config.yaml
          git commit -m "Release ${{ github.ref_name }}"
          git push

      - name: Sign and push Docker image
        env:
          IMAGE: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          VCN_API_KEY: ${{ secrets.VCN_API_KEY }}
        run: |
          docker pull lscr.io/linuxserver/obsidian:latest
          docker tag lscr.io/linuxserver/obsidian:latest "$IMAGE"
          curl -sfL https://getvcn.sh | sh
          vcn login --api-key "$VCN_API_KEY"
          vcn notarize --file codenotary.json docker://$IMAGE
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push "$IMAGE"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ## Release Notes

            See [CHANGELOG.md](CHANGELOG.md) for details.
